version: "3.8"

services:
  # MongoDB Database
  mongo:
    image: mongo:6.0
    container_name: jenkins-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: jenkins_mern_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mern-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js/Express API Server
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: jenkins-server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://root:password123@mongo:27017/jenkins_mern_db?authSource=admin
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mern-network
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  # React Client Application
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: jenkins-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - mern-network

  # Jenkins Server for CI/CD
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-server-ci
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --httpPort=8080
    networks:
      - mern-network

volumes:
  mongo_data:
  jenkins_home:

networks:
  mern-network:
    driver: bridge
